### PR TITLE
Avoid booting providers because they require a Silex\Application instance

### PR DESCRIPTION
**Pull request by Seldaek**
Refs https://github.com/silexphp/Silex/pull/1238

### CODE REVIEW

**Comment by lsmith77** [comment]
looks like some requirements do not work for php 5.3/5.4 which is causing the build failures. 

as for the change can you explain why they shoild not be booted?

**Comment by Seldaek** [comment]
The build failure is independent from my PR really, it's just that Silex bumped the requirement to php 5.5.9 so we should drop the 5.3/5.4 builds here IMO for 2.0

As for why not booting them, as discussed in the linked issue the boot() method requires a Silex\Application, which Cilex\Application is not, so skipping the boot makes everything work fine it just means we might miss some features that are set up in the boot methods but it is seldom used and surely better than a fatal error.

**Comment by stof** [comment]
btw, the order of methods was weird before that. Providers were supposed to subscribe before booting. It was inconsistent with Silex.

**Comment by stof** [comment]
The use statement should be removed too

**Comment by Seldaek** [comment]
OK I removed the use statement and also did a second commit for dependencies/travis update, it's kinda unrelated but while I'm at it it brings this package fully up to speed with Silex 2.0-dev.

**Pull request merged**
